FROM node:alpine
WORKDIR /app
RUN npm install -g pnpm
COPY ./package.json .
COPY ./pnpm-lock.yaml .
COPY ./pnpm-workspace.yaml .

COPY ./turbo.json .
COPY  packages ./packages 
COPY apps/http-backend ./apps/http-backend 




RUN pnpm install


RUN pnpm dlx prisma generate --schema=packages/prisma/prisma/schema.prisma

RUN pnpm build



EXPOSE 3001
CMD ["pnpm","start:backend"]



